server:
  port: 8088
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: us
    password: us
    url: jdbc:h2:mem:micro
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: beans, info
  endpoint:
    beans:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type: debug
